app/views/main.py
from flask import Blueprint, render_template, request, flash, get_flashed_messages, redirect, current_app, url_for
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.models import Posts
from app.forms import PostForm
from flask_login import current_user
from app.exts import db
from app.models import User, Posts
from flask_login import login_required, login_user, logout_user, current_user
import os

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    u = None
    # 判断当前是否登陆
    if current_user.is_authenticated:  # 如果登录
        # 获取当前用户
        u = current_user._get_current_object()
    users1 = User.query.all()
    users = users1[1:5]
    # 获取所有的帖子（按时间顺序）

    posts1 = Posts.query.order_by(Posts.timestamp.desc()).all()
    posts = Posts.query.all()
    posts2 = posts1[:8]

    # 接收用户 url传递过来的 page参数
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    pagination2 = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=8, error_out=False)
    posts3 = pagination.items
    # return render_template('main/index.html', form=form, posts=posts, pagination=pagination)

    return render_template('main/home3.html', user=u, users=users, posts=posts3, pagination=pagination)


# 发布帖子
@main.route('/publish/', methods=['GET', 'POST'])
@login_required
def publish():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:  # 如果登录
            # 获取当前用户
            u = current_user._get_current_object()
            p = Posts(content=form.content.data, user=u)
            db.session.add(p)
            flash('发表成功')
            # 到时候这个跳转要修改
            return redirect(url_for('main.publish'))
        else:
            flash("请先登录")
            return redirect(url_for('users.login'))
    # 调取所有发表的博客
    # posts = Posts.query.filter_by(rid=0).all()
    # www.baidu.com?page=1
    # 接收用户 url传递过来的 page参数
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                        error_out=False)
    posts = pagination.items
    return render_template('posts/publish.html', form=form, posts=posts, pagination=pagination)


@main.route('/more_people')
def more_people():
    users = User.query.all()
    return render_template('main/morePeople.html', users=users)


@main.route('/more_message')
def more_message():
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('main/moreMessage.html', posts=posts, pagination=pagination)


@main.route('/information')
@login_required
def information():
    # 获取当前用户
    u = current_user._get_current_object()
    # 也要获取一遍post数据和pagination数据
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.filter_by(uid=u.id).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                           error_out=False)
    posts = pagination.items
    return render_template('user/userInfo.html', posts=posts, pagination=pagination)


@main.route('/publish_article', methods=['GET', 'POST'])
@login_required
def publish_article():
    # 发布帖子
    form = PostForm()
    if form.validate_on_submit():
        # 获取当前用户
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)
        db.session.add(p)
        flash('发表成功！')
        # 获取到所有的用户自己发表的文章，然后进行显示
        # 接收用户 url传递过来的 page参数
        page = request.args.get('page', 1, type=int)
        pagination = Posts.query.filter_by(uid=u.id).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                               error_out=False)
        posts = pagination.items
    return render_template('posts/publish.html', form=form, posts=posts, pagination=pagination)

app/templates/main/home.html
{% from 'common/macro.html' import message,people,post,pagination_show %}
{% extends 'common/base.html' %}
{% block title %}首页{% endblock %}
{% block styles %}
    {{ supper }}
    <link rel="stylesheet" href="{{ url_for('static',filename="css/common.css") }}">
{% endblock %}
{% block page_content %}
    {% include 'common/kesheheader.html' %}
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">

                <ul id="ul1">
                    <li id="li1">人气推荐</li>
                    <li id="li2">
                        <a href="{{ url_for("main.more_people") }}" class="glyphicon glyphicon-paperclip"
                           aria-hidden="true"></a>
                        <a href="{{ url_for("main.more_people") }}">更多</a>
                    </li>
                </ul>
                <div class="introduce">

                    {{ people(users) }}

                </div>
                <!--帖子-->
                <div class="text">
                    <ul id="ul1">
                        <li id="li1">热帖</li>
                        <li id="li2">
                            <a href="{{ url_for("main.more_message") }}" class="glyphicon glyphicon-paperclip"
                               aria-hidden="true"></a>
                            <a href="{{ url_for("main.more_message") }}">更多</a>
                        </li>
                    </ul>
                    <table class="text_table">
                        <tr>
                            <td id="td1">内容摘要</td>
                            <td id="td11">作者</td>
                            <td id="td12">发表时间</td>
                        </tr>
                        {% for post in posts %}
                            <tr>
                                <td id="td1"><a>{{ post.content }}</a></td>
                                <td id="td11">{{ post.user.username }}</td>
                                <td id="td12">{{ moment(post.timestamp).fromNow() }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    {{ pagination_show(pagination,'main.index') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/home2.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import pagination_show,people,message%}
{% block title %}

    首页
{% endblock %}

{% block page_content %}
{#    <div class="container">#}
{#        <div class="row clearfix">#}
{#            <div class="col-md-6 column">#}
{#                <div class="carousel slide" id="carousel-775341">#}
{#                    <ol class="carousel-indicators">#}
{#                        <li class="active" data-slide-to="0" data-target="#carousel-775341">#}
{#                        </li>#}
{#                        <li data-slide-to="1" data-target="#carousel-775341">#}
{#                        </li>#}
{#                        <li data-slide-to="2" data-target="#carousel-775341">#}
{#                        </li>#}
{#                    </ol>#}
{#                    <div class="carousel-inner">#}
{#                        <div class="item active">#}
{#                            <img src="{{ url_for('static',filename='images/4.jpg') }}"/>#}
{#                            <div class="carousel-caption">#}
{#                                <h4>#}
{#                                    First Thumbnail label#}
{#                                </h4>#}
{#                                <p>#}
{#                                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi#}
{#                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#                                </p>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="item">#}
{#                            <img src="{{ url_for('static',filename='images/5.jpg') }}"/>#}
{#                            <div class="carousel-caption">#}
{#                                <h4>#}
{#                                    Second Thumbnail label#}
{#                                </h4>#}
{#                                <p>#}
{#                                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi#}
{#                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#                                </p>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="item">#}
{#                            <img src="{{ url_for('static',filename='images/6.jpg') }}"/>#}
{#                            <div class="carousel-caption">#}
{#                                <h4>#}
{#                                    Third Thumbnail label#}
{#                                </h4>#}
{#                                <p>#}
{#                                    Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi#}
{#                                    porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.#}
{#                                </p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <a class="left carousel-control" href="#carousel-775341" data-slide="prev"><span#}
{#                            class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control"#}
{#                                                                                    href="#carousel-775341"#}
{#                                                                                    data-slide="next"><span#}
{#                        class="glyphicon glyphicon-chevron-right"></span></a>#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-4 column">#}
{#                <h2>#}
{#                    每日精选#}
{#                </h2>#}
{#                <ul style="margin: 20px">#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/renshengzheli/chenggong/20070905/914.html">要养成成功的习惯</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/shige/shuqingshi/20190114/398414.html">花开不败香自来</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/youqingwenzhang/20070828/853.html">友谊是一株树</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/shenghuosuibi/shenghuoganwu/20181015/395031.html">时间面前，一切终将释怀</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/renshengzheli/20190107/398150.html">当你改变不了环境的时候，试着改变自己</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/youqingwenzhang/20070808/621.html">关于友情</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/jingdianwenzhang/20070712/174.html">世界上最快乐的事</a></li>#}
{#                    <li><a href="http://www.duwenzhang.com/wenzhang/jingdianwenzhang/20070714/232.html">经营好自己一生中的三天</a></li>#}
{##}
{#                </ul>#}
{#                <p>#}
{#                    <a class="btn" href="{{ url_for('main.index') }}">View details »</a>#}
{#                </p>#}
{#            </div>#}
{#        </div>#}
{#        <div class="row clearfix" style="margin-top: 50px">#}
{#            <div class="col-md-12 column">#}
{#                <blockquote>#}
{#                    <p>#}
{#                        Good company on the road is the shortest cut.#}
{#                    </p>#}
{#                </blockquote>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <div class="container">
	    <div class="row clearfix">
		<div class="col-md-12 column">
{#			<ul class="breadcrumb">#}
{#				<li>#}
{#					 <a href="{{ url_for("main.index") }}">Home</a>#}
{#				</li>#}
{#				<li>#}
{#					 <a href="{{ url_for("main.publish") }}">我要发帖</a>#}
{#				</li>#}
{#                <li>#}
{#                    <a href="{{ url_for('main.information') }}">#}
{#                        进入个人中心#}
{#                    </a>#}
{#                </li>#}
{#			</ul>#}
            <ul id="ul1">
                    <li id="li1">人气推荐</li>
                    <li id="li2">
                        <a href="{{ url_for("main.more_people")}}" class="glyphicon glyphicon-paperclip" aria-hidden="true"></a>
                        <a href="{{ url_for("main.more_people") }}">更多</a>
                    </li>
            </ul>
			<div class="introduce">
{#                <div class="introduce1">#}
{#                    <div style="float:left;border:1px solid red;">#}
{#                        <img id="img" src="static/images/header2.jpg" >#}
{#                    </div>#}
{#                    <div id="divIntro">#}
{#                        <div id="divN">{{ username }}</div>#}
{#                        <div id="divG">#}
{#                            <a href="#"><button>关注</button></a>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="introduce1">#}
{#                    <div style="float:left;border:1px solid red;">#}
{#                        <img id="img" src="static/images/header2.jpg">#}
{#                    </div>#}
{#                    <div id="divIntro">#}
{#                        <div id="divN">{{ username }}</div>#}
{#                        <div id="divG">#}
{#                            <a href="#"><button>关注</button></a>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                </div>#}
{#                <div class="introduce1">#}
{#                    <div style="float:left;border:1px solid red;">#}
{#                        <img id="img" src="static/images/header2.jpg">#}
{#                    </div>#}
{#                    <div id="divIntro">#}
{#                        <div id="divN">{{ username }}</div>#}
{#                        <div id="divG">#}
{#                            <a href="#"><button>关注</button></a>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                </div>#}
{#                <div class="introduce1">#}
{#                    <div style="float:left;border:1px solid red;">#}
{#                        <img id="img"   src="static/images/header1.jpg" >#}
{#                    </div>#}
{#                    <div id="divIntro">#}
{#                        <div id="divN">{{ username }}</div>#}
{#                        <div id="divG">#}
{#                            <a href="#"><button >关注</button></a>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                </div>#}
                {{ people(users)}}
{#                {% for i in range(4) %}#}
{#                    {{ peopleFiled("images/header1.jpg",username) }}#}
{#                {% endfor %}#}

            </div>
            <!--帖子-->
            <div class="text">
                <ul id="ul1">
                    <li id="li1">热帖</li>
                    <li id="li2">
                        <a href="{{ url_for("main.more_message")}}" class="glyphicon glyphicon-paperclip" aria-hidden="true"></a>
                        <a href="{{ url_for("main.more_message")}}">更多</a>
                    </li>
                </ul>
                <table class="text_table">
                    <tr>
                        <td>标题</td>
                        <td>发帖人</td>
                        <td>回复数</td>
                        <td>人气</td>
                    </tr>
{#                    {% for message in messages %}#}
{#                        <tr>#}
{#                            <td id="td3"><a href="#">{{ message.title }}</a></td>#}
{#                            <td id="td4">{{ message.author }}</td>#}
{#                            <td id="td4">{{ message.answerCounts }}</td>#}
{#                            <td id="td4">{{ message.zan }}</td>#}
{#                        </tr>#}
{#                    {% endfor %}#}
{#                    {{ message(messages,'main.index') }}#}
                </table>
            </div>
		</div>
	</div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/main/home3.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import message,people,post,pagination_show %}
{% block title %}
    shouye
{% endblock %}
{% block styles %}
    {{ supper }}
    <link rel="stylesheet" href="{{ url_for('static',filename="css/common.css") }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
{% endblock %}
{#{% block navbar %}#}
{#这是导航栏#}
{#{% endblock %}#}
{% block page_content %}
     <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">

                <ul id="ul1">
                    <li id="li1">人气推荐</li>
                    <li id="li2">
                        <a href="{{ url_for("main.more_people") }}" class="glyphicon glyphicon-paperclip"
                           aria-hidden="true"></a>
                        <a href="{{ url_for("main.more_people") }}">更多</a>
                    </li>
                </ul>
                <div class="introduce">

                    {{ people(users) }}

                </div>
                <!--帖子-->
                <div class="text">
                    <ul id="ul1">
                        <li id="li1">热帖</li>
                        <li id="li2">
                            <a href="{{ url_for("main.more_message") }}" class="glyphicon glyphicon-paperclip"
                               aria-hidden="true"></a>
                            <a href="{{ url_for("main.more_message") }}">更多</a>
                        </li>
                    </ul>
                    <table class="text_table">
                        <tr>
                            <td id="td1">内容摘要</td>
                            <td id="td11">作者</td>
                            <td id="td12">发表时间</td>
                        </tr>
                        {% for post in posts %}
                            <tr>
                                <td id="td1"><a>{{ post.content }}</a></td>
                                <td id="td11">{{ post.user.username }}</td>
                                <td id="td12">{{ moment(post.timestamp).fromNow() }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    <div style="margin-left:420px">
                        {{ pagination_show(pagination,'main.index') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/main/index.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import pagination_show%}
{% block title %}

    首页
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
    {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                {{ post.content }}
                ...
            </div>
        </div>
    {% endfor %}
    {{ pagination_show(pagination,'main.index') }}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/main/moreMessage.html
{% include 'common/kesheheader.html' %}
{% from 'common/macro.html' import pagination_show %}
{#{% block title %}博主表单{% endblock %}#}
{% block page_content %}
    <ul class="mpul">博客列表</ul>
    <div class="mPeople">
        {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                {{ post.content }}
                ...
            </div>
        </div>
    {% endfor %}
    {{ pagination_show(pagination,'main.more_message') }}
    </div>
{% endblock %}
{% block scripts %}
{#    {{ super() }}#}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/main/morePeople.html
{% include 'common/kesheheader.html' %}
{#{% from 'common/macros.html' import peopleFiled %}#}
{#{% block title %}博主表单{% endblock %}#}
{% block scripts %}
{% endblock %}
{% block body %}
    <ul class="mpul">博主列表</ul>
    <div class="mPeople">
        {% for user in users %}
            <div class="introduce2">
                <div style="float:left;border:1px solid red;">
                    <img id="img" src="{{ url_for('static',filename='upload/'+user.icon) }}">
{#                    <img src="static/images/header2.jpg" width="100%" height="100px">#}
                </div>
                <div id="divIntro">
                    <div id="divN">{{ user.username }}</div>
                    <div id="divG">
                        <a href="#">
                            <button>关注</button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


{% endblock %}

app/templates/main/myArticle.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import pagination_show%}
{% block title %}
    我的帖子
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
    {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                {{ post.content }}
                ...
            </div>
        </div>
    {% endfor %}
    {{ pagination_show(pagination,'main.publish') }}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}