app/views/main.py
from flask import Blueprint, render_template, request, flash, get_flashed_messages, redirect, current_app, url_for
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.models import Posts
from app.forms import PostForm
from flask_login import current_user
from app.exts import db
from app.models import User, Posts
from flask_login import login_required, login_user, logout_user, current_user
import os

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    u = None
    # 判断当前是否登陆
    if current_user.is_authenticated:  # 如果登录
        # 获取当前用户
        u = current_user._get_current_object()
    users1 = User.query.all()
    users = users1[1:5]
    # 获取所有的帖子（按时间顺序）

    posts1 = Posts.query.order_by(Posts.timestamp.desc()).all()
    posts = Posts.query.all()
    posts2 = posts1[:8]

    # 接收用户 url传递过来的 page参数
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    pagination2 = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=8, error_out=False)
    posts3 = pagination.items
    # return render_template('main/index.html', form=form, posts=posts, pagination=pagination)

    return render_template('main/home3.html', user=u, users=users, posts=posts3, pagination=pagination)


# 发布帖子
@main.route('/publish/', methods=['GET', 'POST'])
@login_required
def publish():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:  # 如果登录
            # 获取当前用户
            u = current_user._get_current_object()
            p = Posts(content=form.content.data, user=u)
            db.session.add(p)
            flash('发表成功')
            # 到时候这个跳转要修改
            return redirect(url_for('main.publish'))
        else:
            flash("请先登录")
            return redirect(url_for('users.login'))
    # 调取所有发表的博客
    # posts = Posts.query.filter_by(rid=0).all()
    # www.baidu.com?page=1
    # 接收用户 url传递过来的 page参数
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                        error_out=False)
    posts = pagination.items
    return render_template('posts/publish.html', form=form, posts=posts, pagination=pagination)


@main.route('/more_people')
def more_people():
    users = User.query.all()
    return render_template('main/morePeople.html', users=users)


@main.route('/more_message')
def more_message():
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.order_by(Posts.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('main/moreMessage.html', posts=posts, pagination=pagination)


@main.route('/information')
@login_required
def information():
    # 获取当前用户
    u = current_user._get_current_object()
    # 也要获取一遍post数据和pagination数据
    page = request.args.get('page', 1, type=int)
    pagination = Posts.query.filter_by(uid=u.id).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                           error_out=False)
    posts = pagination.items
    return render_template('user/userInfo.html', posts=posts, pagination=pagination)


@main.route('/publish_article', methods=['GET', 'POST'])
@login_required
def publish_article():
    # 发布帖子
    form = PostForm()
    if form.validate_on_submit():
        # 获取当前用户
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)
        db.session.add(p)
        flash('发表成功！')
        # 获取到所有的用户自己发表的文章，然后进行显示
        # 接收用户 url传递过来的 page参数
        page = request.args.get('page', 1, type=int)
        pagination = Posts.query.filter_by(uid=u.id).order_by(Posts.timestamp.desc()).paginate(page, per_page=5,
                                                                                               error_out=False)
        posts = pagination.items
    return render_template('posts/publish.html', form=form, posts=posts, pagination=pagination)

app/views/users.py
import os
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, current_app
from app.forms import RegisterForm, LoginForm, UploadForm, PasswordForm, FindPassword, InputPassword, ChangeEmailForm
from app.models import User
from app.exts import db, photos
from app.email import send_mail
from flask_login import login_required, login_user, logout_user, current_user
from PIL import Image
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

users = Blueprint('users', __name__)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(u)
        db.session.commit()

        # 生成token  用u对象调用模型中的方法
        token = u.generate_active_token()
        send_mail(u.email, '账户激活', 'email/activate', username=u.username, token=token)
        flash("恭喜注册成功,请点击邮件中的链接完成激活")
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/active/<token>', methods=['GET', 'POST'])
def active(token):
    if User.check_active_token(token):
        flash("账户激活成功")
        return redirect(url_for('users.login'))
    else:
        flash("账户激活失败")
        return redirect(url_for('main.index'))


# 登陆
@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在")
        elif not u.confirmed:
            flash("该账户没有激活,请激活后登录")
        elif u.verify_password(form.password.data):
            login_user(u, remember=form.remember.data)
            flash("登录成功")
            return redirect(request.args.get('next') or url_for("main.index"))
        else:
            flash("密码不正确")
    return render_template('user/login2.html', form=form)


@users.route('/logout/', methods=['GET', 'POST'])
def logout():
    logout_user()
    flash("退出登录成功")
    return redirect(url_for('main.index'))


@users.route('/test/', methods=['GET', 'POST'])
@login_required
def test():
    return 'this is test'


# 修改头像
@users.route('/change_icon/', methods=['GET', 'POST'])
@login_required
def change_icon():
    img_url = ''
    form = UploadForm()
    if form.validate_on_submit():
        # 获取文件后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 随机文件名  拼接
        filename = random_string() + suffix
        photos.save(form.icon.data, name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        flash(pathname)
        img = Image.open(pathname)
        img.thumbnail((128, 128))
        img.save(pathname)
        # 这里，判断用户的头像是否为默认头像
        if current_user.icon != 'default.jpg':
            remove_name = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon)
            os.remove(remove_name)
        current_user.icon = filename  # 将新上传的文件名 赋值给 用户的头像
        db.session.add(current_user)  # 保存在数据库中
        flash("头像上传成功")
        return redirect(url_for("users.change_icon"))
    img_url = photos.url(current_user.icon)
    return render_template('user/change_icon.html', form=form, img_url=img_url)


def random_string(length=20):
    import random
    base_str = 'abc123defhijklmnopqrstuvwxyz4567890'
    return ''.join(random.choice(base_str) for i in range(length))


# 修改邮箱
@users.route('/change_email/', methods=['GET', 'POST'])
@login_required
def change_email():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == current_user.username).first()
        if user.verify_password(form.password.data):
            current_user.email = form.email.data
            db.session.add(current_user)
            flash("修改成功")
            return redirect(url_for("users.information"))
        else:
            flash('用户名或密码输入错误')
    return render_template('user/change_email.html', form=form)


# 修改密码
@users.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.pre_password.data):
            # 首先要验证旧密码的正确性,如果错误要有处理
            current_user.password = form.new_password.data
            db.session.add(current_user)
            flash('修改密码成功')
            return redirect(url_for('main.index'))
        else:
            flash('修改密码失败，请重新尝试')
    return render_template('user/change_password.html', form=form)


# 找回密码
@users.route('/find_password/', methods=['GET', 'POST'])
def find_password():
    form = FindPassword()
    if form.validate_on_submit():
        # 获得当前的用户  根据填入的username
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在，请重新输入")
        # elif current_user.username != u.username:
        #     flash("请输入您自己的正确的用户名")
        else:
            # 发送邮件，找回密码（修改密码）
            # 生成token  用u对象调用模型中的方法
            token = u.generate_active_token()
            send_mail(u.email, '找回密码', 'email/find', username=u.username, token=token)
            flash("链接已发送到邮箱，请点击邮箱中的链接找回密码")
    return render_template('user/find_password.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/check_token/<token>', methods=['GET', 'POST'])
def check_token(token):
    if User.check_active_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            # return False
            flash('点击链接时操作失败')
        # 这个id是从 token中解析出来的  然后根据id 到数据库中查找  对应的数据进行更新
        u = User.query.get(data.get('id'))
        if not u:
            flash("该用户不存在，请重新尝试")
            return redirect(url_for('users.index'))
        else:
            ## 用户点击了链接，跳转到修改密码的界面进行修改
            # return redirect(url_for('users.input_password'))
            form = InputPassword()
            if form.validate_on_submit():
                # 表单数据验证成功
                u.password = form.new_password.data
                db.session.add(u)
                flash('修改密码成功，请登陆')
                return redirect(url_for('users.login'))
            else:
                flash('input修改密码失败，请重新尝试')
            return render_template('user/inputPassword.html', form=form)
    else:
        flash("check_token,密码修改失败")
        return redirect(url_for('main.index'))


# 填写新的密码的操作
@users.route('/input_password/', methods=['GET', 'POST'])
def input_password():
    form = InputPassword()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        db.session.add(current_user)
        flash('修改密码成功')
        return redirect(url_for('main.index'))
    else:
        flash('input修改密码失败,请重新尝试')
    return render_template('user/inputPassword.html', form=form)


# 查看个人资料
@users.route('/information')
def information():
    return render_template('user/userInfo.html')

app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{#定制标题#}
{% block title %}默认标题{% endblock %}
{#定制导航条#}
{% block navbar %}
    <nav style="height:50px">

        <!-- Brand and toggle get grouped for better mobile display -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div style="height:100%">
            <ul class="breadcrumb">
                <li>
                    <a href="{{ url_for("main.index") }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for("main.publish") }}">我要发帖</a>
                </li>
                <li>
                    <a href="{{ url_for('main.information') }}">
                        进入个人中心
                    </a>
                </li>
                {% if current_user.is_authenticated %}

                    <li style="float:right;list-style-type: none;" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">你好，{{ current_user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">

                            <li><a href="{{ url_for('users.change_password') }}">修改密码</a></li>
                            <li><a href="{{ url_for('users.change_email') }}">修改邮箱</a></li>
                            <li><a href="{{ url_for('users.change_icon') }}">修改头像</a></li>
                            <li role="separator" class="divider"></li>

                            <li><a href="{{ url_for('main.information') }}">个人中心</a></li>
                        </ul>
                    </li>
                    <li style="float:right;list-style-type: none;"><a href="{{ url_for('users.logout') }}">退出</a></li>
                        {% else %}
                            <li style="float:right;list-style-type: none;"><a href="{{ url_for('users.register') }}">注册</a></li>
                            <li style="float:right;list-style-type: none;"><a href="{{ url_for('users.login') }}">登陆</a></li>
                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->

    </nav>
{% endblock %}
{#定制内容 #}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>Warning!</strong>{{ message }}
            </div>
        {% endfor %}

        {% block page_content %}
            默认内容
        {% endblock %}
    </div>
{% endblock %}
{#定制脚本#}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/common/home.html
{% block head %}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename='images/favicon.ico') }}">
{% endblock %}
{% block body %}
    {% include 'common/kesheheader.html' %}
    <div class="container">
	    <div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="breadcrumb">
				<li>
					 <a href="#">Home</a>
				</li>
				<li>
					 <a href="#">我要发帖</a>
				</li>
			</ul>
            <ul id="ul1">
                    <li id="li1">人气推荐</li>
                    <li id="li2">
                        <a href="{{ url_for("more_messages")}}" class="glyphicon glyphicon-paperclip" aria-hidden="true"></a>
                        <a href="{{ url_for("more_people") }}">更多</a>
                    </li>
            </ul>

            {{ people(users) }}

                </div>
            </div>
            <!--帖子-->
            <div class="text">
                <ul id="ul1">
                    <li id="li1">热帖</li>
                    <li id="li2">
                        <a href="{{ url_for("more_messages")}}" class="glyphicon glyphicon-paperclip" aria-hidden="true"></a>
                        <a href="{{ url_for("more_messages")}}">更多</a>
                    </li>
                </ul>
                <table class="text_table">
                    <tr>
                        <td>标题</td>
                        <td>发帖人</td>
                        <td>回复数</td>
                        <td>人气</td>
                    </tr>
                    {% for message in messages %}
                        <tr>
                            <td id="td3"><a href="#">{{ message.title }}</a></td>
                            <td id="td4">{{ message.author }}</td>
                            <td id="td4">{{ message.answerCounts }}</td>
                            <td id="td4">{{ message.zan }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
		</div>
	</div>
    </div>
{% endblock %}

app/templates/common/kesheheader.html
{% block head %}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename='images/favicon.ico') }}">
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static',filename="css/common.css") }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static',filename="js/common.js") }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %}
{% block navbar %}
    {#    <div class="container">#}
    {#        <div class="row clearfix">#}
    {#            <div class="col-md-8 column" id="col-md-8 column" style="width:1005px;">#}
    {#                <img alt="140x140" src="static/images/head.jpg" width="100%" height="120px"/>#}
    {#            </div>#}
    {#            <div class="col-md-4 column" id="col-md-4">#}
    {#                {% if user %}#}
    {#                    <div id="user">#}
    {#                        <span>你好，{{ user.username }}</span>#}
    {#                    </div>#}
    {##}
    {#                {% else %}#}
    {#                    <a href="{{ url_for("users.login") }}">登陆</a>#}
    {#                    <a href="{{ url_for("users.register") }}">注册</a>#}
    {#                {% endif %}#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
{#    <nav class="navbar navbar-default">#}
{#        <div class="container-fluid">#}
{#            <!-- Brand and toggle get grouped for better mobile display -->#}
{#            <div class="navbar-header">#}
{#                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"#}
{#                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">#}
{#                    <span class="sr-only">Toggle navigation</span>#}
{#                    <span class="icon-bar"></span>#}
{#                    <span class="icon-bar"></span>#}
{#                    <span class="icon-bar"></span>#}
{#                </button>#}
{#                <a class="navbar-brand" href="#">首页</a>#}
{#            </div>#}
{##}
{#            <!-- Collect the nav links, forms, and other content for toggling -->#}
{#            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#                <ul class="nav navbar-nav">#}
{#                    <li class="active"><a href="#">博客 <span class="sr-only">(current)</span></a></li>#}
{#                    <li><a href="#">新闻</a></li>#}
{#                </ul>#}
{#                <ul class="nav navbar-nav navbar-right">#}
{#                    {% if current_user.is_authenticated %}#}
{#                        <li><a href="{{ url_for('users.logout') }}">退出</a></li>#}
{#                    <li class="dropdown">#}
{#                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                           aria-expanded="false">你好,{{ current_user.username }} <span class="caret"></span></a>#}
{#                        <ul class="dropdown-menu">#}
{#                            <li><a href="#">个人中心</a></li>#}
{#                            <li><a href="#">修改密码</a></li>#}
{#                            <li><a href="#">修改邮箱</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li><a href="{{ url_for("users.change_icon") }}">修改头像</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                        {% else %}#}
{#                        <li><a href="{{ url_for("users.login") }}">登录</a></li>#}
{#                        <li><a href="{{ url_for("users.register") }}">注册</a></li>#}
{#                    {% endif %}#}
{#                </ul>#}
{#            </div><!-- /.navbar-collapse -->#}
{#        </div><!-- /.container-fluid -->#}
{#    </nav>#}
{#    {{ supper }}#}
{% endblock %}

app/templates/common/macro.html
{#第一个参数 pagination对象 第二个 跳转到哪里去#}
{% macro pagination_show(pagination,endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {#      上一页#}
            <li {% if not pagination.has_prev %} class="disabled" {% else %} {% endif %}>
                <a href="


                        {% if pagination.has_prev %}{{ url_for(endpoint,page=pagination.prev_num,**kwargs) }}{% else %}#{% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {#      中间页码#}
            {% for p in pagination.iter_pages() %}
                {% if p %}
                    {#            www.baidu.com?page=#}
                    <li {% if pagination.page == p %} class="active" {% endif %}><a
                            href="{{ url_for(endpoint,page=p,**kwargs) }}">{{ p }}</a></li>
                {% else %}
                    <li><a href="#">&hellip;</a></li>
                {% endif %}

            {% endfor %}
            {#      下一页#}
            <li {% if not pagination.has_next %} class="disabled" {% else %}{% endif %}>
                <a href="


                        {% if pagination.has_next %}{{ url_for(endpoint,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}"
                   aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

{% macro message(messages) %}
    {% for message in messages %}
        <tr>
            <td id="td3"><a href="#">{{ message.title }}</a></td>
            <td id="td4">{{ message.author }}</td>
            <td id="td4">{{ message.answerCounts }}</td>
            <td id="td4">{{ message.zan }}</td>
        </tr>
    {% endfor %}
{% endmacro %}
{% macro people(users) %}
    {% for user in users %}
        <div class="introduce1">
            <div style="float:left;border:1px solid red;">
{#                os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],user.icon)#}
{#                <img id="img" src="{{ 'static\upload\'+user.icon }}">#}
                <img id="img" src="{{ url_for('static',filename='upload/'+user.icon) }}">
            </div>
            <div id="divIntro">
                <div id="divN">{{ user.username }}</div>
                <div id="divG">
                    <a href="#">
                        <button>关注</button>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}
{% macro post(posts) %}
    {% for post in posts %}
        <tr>
            <td id="td1">{{ post.content }}</td>
            <td id="td2">{{ post.user.username }}</td>
{#            <td id="td3">{{ moment(post.timestamp).fromNow() }}</td>#}
            <td id="td3">{{ post.timestamp }}</td>
        </tr>
    {% endfor %}
{% endmacro %}