app/models/users.py
from app.exts import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app, flash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from app.exts import login_manager


# UserMixin 查看该用户是否登录 以及 是否是匿名用户

class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
    username = db.Column(db.String(50), nullable=False, unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(128), nullable=False, unique=True)
    confirmed = db.Column(db.Boolean, default=False)
    icon = db.Column(db.String(64), default='default.jpg')
    # lazy 在这里是懒加载 dynamic表示不加载数据但是提供查询
    # 如果一对一的关系 需要加上 uselist=Flase
    posts = db.relationship("Posts", backref="user", lazy="dynamic")

    # 当前用户通过 user 访问 posts 表中的字段
    # 密码不能读 而且永不返回
    @property
    def password(self):
        raise AttributeError("密码不可读的帅哥")

    # 设置密码的时候  保存的是加密后的hash值
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 校验密码是否正确 正确 true 错误 false
    # 先加密 再跟数据库比较
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 生成token   通过邮箱发送给用户
    def generate_active_token(self, expires_in=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expires_in)
        return s.dumps({'id': self.id})

    # 验证token 方法
    @staticmethod
    def check_active_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        # 这个id是从 token中解析出来的  然后根据id 到数据库中查找  对应的数据进行更新
        u = User.query.get(data.get('id'))
        if not u:
            flash("该用户不存在")
            return False
        if not u.confirmed:
            u.confirmed = True
            db.session.add(u)
        return True


# 登录成功以后 执行以下方法 回调函数 获取登录用户的相关信息
@login_manager.user_loader
def load_user(uid):
    return User.query.get(int(uid))

app/forms/users.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, Email
from wtforms.validators import ValidationError
from flask_wtf.file import FileField, FileRequired, FileAllowed
from app.models import User  # 自定义验证函数 用户提交检测数据中是否存在
from app.exts import photos  # 只能上传图片


# 用户注册表单
class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6, 20, message="用户名必须在6到20位之间")])
    email = StringField('Email', validators=[Email(message="邮箱格式不正确")])
    password = PasswordField('密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    confirm = PasswordField('确认密码', validators=[EqualTo('password', message="两次密码不一致")])
    submit = SubmitField('立即注册')

    def validate_username(self, filed):
        if User.query.filter_by(username=filed.data).first():
            raise ValidationError("该用户已经注册请选择其它用户")

    def validate_email(self, filed):
        if User.query.filter_by(email=filed.data).first():
            raise ValidationError("该邮箱已经被占用请用其它邮箱")


# 用户登录表单
class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6, 20, message="用户名必须在6到20位之间")])
    password = PasswordField('密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    remember = BooleanField('记住我')
    submit = SubmitField('立即登录')


# 用户上传表单
class UploadForm(FlaskForm):
    icon = FileField("头像", validators=[FileRequired(), FileAllowed(photos, message="只能上传图片类型")])
    submit = SubmitField('立即上传')


# 修改密码表单
class PasswordForm(FlaskForm):
    pre_password = PasswordField('原密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    new_password = PasswordField('新密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    confirm = PasswordField('确认密码', validators=[EqualTo('new_password', message="两次密码不一致")])
    submit = SubmitField('确认修改')


# 找回密码表单
class FindPassword(FlaskForm):
    # email = StringField('Email', validators=[Email(message="邮箱格式不正确")])
    username = StringField('请填入用户名', validators=[DataRequired(), Length(6, 20, message="用户名必须在6到20位之间")])
    submit = SubmitField('确认修改')


# 填入新密码表单
class InputPassword(FlaskForm):
    new_password = PasswordField('新密码', validators=[DataRequired(), Length(6, 20, message="密码在6-20个字之间")])
    confirm = PasswordField('确认密码', validators=[DataRequired(), EqualTo('new_password', message="两次密码不一致")])
    submit = SubmitField('确认修改')


# 修改邮箱表单
class ChangeEmailForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6, 20, message="用户名必须在6到20位之间")])
    password = PasswordField('密码', validators=[DataRequired(), Length(6, 20, message="密码长度必须在6到20位之间")])
    email = StringField('新邮箱', validators=[Email(message="邮箱格式不正确")])
    submit = SubmitField('立即修改')

app/views/users.py
import os
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, current_app
from app.forms import RegisterForm, LoginForm, UploadForm, PasswordForm, FindPassword, InputPassword, ChangeEmailForm
from app.models import User
from app.exts import db, photos
from app.email import send_mail
from flask_login import login_required, login_user, logout_user, current_user
from PIL import Image
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

users = Blueprint('users', __name__)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(u)
        db.session.commit()

        # 生成token  用u对象调用模型中的方法
        token = u.generate_active_token()
        send_mail(u.email, '账户激活', 'email/activate', username=u.username, token=token)
        flash("恭喜注册成功,请点击邮件中的链接完成激活")
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/active/<token>', methods=['GET', 'POST'])
def active(token):
    if User.check_active_token(token):
        flash("账户激活成功")
        return redirect(url_for('users.login'))
    else:
        flash("账户激活失败")
        return redirect(url_for('main.index'))


# 登陆
@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在")
        elif not u.confirmed:
            flash("该账户没有激活,请激活后登录")
        elif u.verify_password(form.password.data):
            login_user(u, remember=form.remember.data)
            flash("登录成功")
            return redirect(request.args.get('next') or url_for("main.index"))
        else:
            flash("密码不正确")
    return render_template('user/login2.html', form=form)


@users.route('/logout/', methods=['GET', 'POST'])
def logout():
    logout_user()
    flash("退出登录成功")
    return redirect(url_for('main.index'))


@users.route('/test/', methods=['GET', 'POST'])
@login_required
def test():
    return 'this is test'


# 修改头像
@users.route('/change_icon/', methods=['GET', 'POST'])
@login_required
def change_icon():
    img_url = ''
    form = UploadForm()
    if form.validate_on_submit():
        # 获取文件后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 随机文件名  拼接
        filename = random_string() + suffix
        photos.save(form.icon.data, name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        flash(pathname)
        img = Image.open(pathname)
        img.thumbnail((128, 128))
        img.save(pathname)
        # 这里，判断用户的头像是否为默认头像
        if current_user.icon != 'default.jpg':
            remove_name = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon)
            os.remove(remove_name)
        current_user.icon = filename  # 将新上传的文件名 赋值给 用户的头像
        db.session.add(current_user)  # 保存在数据库中
        flash("头像上传成功")
        return redirect(url_for("users.change_icon"))
    img_url = photos.url(current_user.icon)
    return render_template('user/change_icon.html', form=form, img_url=img_url)


def random_string(length=20):
    import random
    base_str = 'abc123defhijklmnopqrstuvwxyz4567890'
    return ''.join(random.choice(base_str) for i in range(length))


# 修改邮箱
@users.route('/change_email/', methods=['GET', 'POST'])
@login_required
def change_email():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == current_user.username).first()
        if user.verify_password(form.password.data):
            current_user.email = form.email.data
            db.session.add(current_user)
            flash("修改成功")
            return redirect(url_for("users.information"))
        else:
            flash('用户名或密码输入错误')
    return render_template('user/change_email.html', form=form)


# 修改密码
@users.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.pre_password.data):
            # 首先要验证旧密码的正确性,如果错误要有处理
            current_user.password = form.new_password.data
            db.session.add(current_user)
            flash('修改密码成功')
            return redirect(url_for('main.index'))
        else:
            flash('修改密码失败，请重新尝试')
    return render_template('user/change_password.html', form=form)


# 找回密码
@users.route('/find_password/', methods=['GET', 'POST'])
def find_password():
    form = FindPassword()
    if form.validate_on_submit():
        # 获得当前的用户  根据填入的username
        u = User.query.filter_by(username=form.username.data).first()
        if not u:
            flash("该用户名不存在，请重新输入")
        # elif current_user.username != u.username:
        #     flash("请输入您自己的正确的用户名")
        else:
            # 发送邮件，找回密码（修改密码）
            # 生成token  用u对象调用模型中的方法
            token = u.generate_active_token()
            send_mail(u.email, '找回密码', 'email/find', username=u.username, token=token)
            flash("链接已发送到邮箱，请点击邮箱中的链接找回密码")
    return render_template('user/find_password.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/check_token/<token>', methods=['GET', 'POST'])
def check_token(token):
    if User.check_active_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            # return False
            flash('点击链接时操作失败')
        # 这个id是从 token中解析出来的  然后根据id 到数据库中查找  对应的数据进行更新
        u = User.query.get(data.get('id'))
        if not u:
            flash("该用户不存在，请重新尝试")
            return redirect(url_for('users.index'))
        else:
            ## 用户点击了链接，跳转到修改密码的界面进行修改
            # return redirect(url_for('users.input_password'))
            form = InputPassword()
            if form.validate_on_submit():
                # 表单数据验证成功
                u.password = form.new_password.data
                db.session.add(u)
                flash('修改密码成功，请登陆')
                return redirect(url_for('users.login'))
            else:
                flash('input修改密码失败，请重新尝试')
            return render_template('user/inputPassword.html', form=form)
    else:
        flash("check_token,密码修改失败")
        return redirect(url_for('main.index'))


# 填写新的密码的操作
@users.route('/input_password/', methods=['GET', 'POST'])
def input_password():
    form = InputPassword()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        db.session.add(current_user)
        flash('修改密码成功')
        return redirect(url_for('main.index'))
    else:
        flash('input修改密码失败,请重新尝试')
    return render_template('user/inputPassword.html', form=form)


# 查看个人资料
@users.route('/information')
def information():
    return render_template('user/userInfo.html')

app/templates/user/change_email.html
{% extends 'common/base.html' %}
{% block title %}修改邮箱
{% endblock %}
{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/change_icon.html
{% extends 'common/base.html' %}

{% block title %}修改头像
{% endblock %}

{% block page_content %}
    <img src="{{ img_url }}" alt="美女">
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/change_password.html
{% extends 'common/base.html' %}

{% block title %}
    修改密码
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/find_password.html
{% extends 'common/base.html' %}

{% block title %}
    找回密码
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/gerenzhongxin.html
<div>
    <a href="#">修改头像</a>
</div>
</div>
</div>
</nav>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <ul class="panel-heading" style="height: 40px">
        <li style="list-style: none;float: left">我的帖子</li>
        <li style="list-style: none;float: right">我要发帖</li>
    </ul>
    <!-- Table -->
    <table class="table">
        <tr>
            <td>#</td>
            <td>标题</td>
            <td>内容</td>
        </tr>
        <tr>
            <td>1</td>
            <td>{{ post.user.title }}</td>
            <td>{{ post.content }}</td>
        </tr>
        <tr>
            <td>2</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>3</td>
            <td></td>
            <td></td>
        </tr>
    </table>

    <nav aria-label="Page navigation" style="margin-left:550px ">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

</nav>

</body>
</html>

app/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
user首页
</body>
</html>

app/templates/user/inputPassword.html
{% extends 'common/base.html' %}

{% block title %}
    修改密码
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/login.html
{% extends 'common/base.html' %}

{% block title %}
登录页面
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/login2.html
{% extends 'common/base.html' %}

{% block title %}
    登录页面
{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-8 column">
                <div class="row">
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <img src="{{ url_for('static',filename='images/1.jpg') }}"/>
                            <div class="caption">
                                <h3>
                                    Daily Sentence
                                </h3>
                                <p>
                                    Don't aim for success if you want it; just do what you love and believe in, and it
                                    will come naturally.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <img src="{{ url_for('static',filename='images/2.jpg') }}"/>
                            <div class="caption">
                                <h3>
                                    Daily Sentence
                                </h3>
                                <p>
                                    The shortest way to do many things is to only one thing at a time.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <img src="{{ url_for('static',filename='images/3.jpg') }}"/>
                            <div class="caption">
                                <h3>
                                     Daily Sentence
                                </h3>
                                <p>
                                    There are moments in life when you miss someone so much that you just want to pick
                                    them from your dreams and hug them for real! Dream what you want to dream.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 column">
                {{ wtf.quick_form(form) }}
                <a href="{{ url_for('users.find_password') }}">找回密码</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
     <div class="row clearfix" style="margin-left: 200px">
            <div class="col-md-12 column">
                <p>
                    没有账号？点击<a href="{{ url_for('users.register') }}">立即注册</a>让我们一起探索世界的奥妙！
                </p>
            </div>
        </div>
{% endblock %}

app/templates/user/register.html
{% extends 'common/base.html' %}

{% block title %}
注册页面
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/userInfo.html
{% from 'common/macro.html' import pagination_show %}
{#{% extends 'common/base.html' %}#}
{% block content %}
    {% include 'common/kesheheader.html' %}
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <ul class="nav nav-tabs" style="height:40px">
                    <li class="active">
                        <a href="{{ url_for('main.index') }}">返回首页</a>
                    </li>
                    <li class="disabled">
                        <a href="#">个人中心</a>
                    </li>
                    <li class="dropdown pull-right">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">修改<strong class="caret"></strong></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ url_for('users.change_password') }}">修改密码</a>
                            </li>
                            <li>
                                <a href="{{ url_for('users.change_email') }}">修改邮箱</a>
                            </li>
                            <li>
                                <a href="{{ url_for('users.change_icon') }}">修改头像</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-6 column">
                <ul id="ul1"><li id="li1" style="font-size:14px;margin-left:-35px;">个人基本资料</li></ul>
                <div id="inf1">
                    <div class="inf1">
                        <div class="div_icon">
                            <img class="Icon" src="static/upload/{{ current_user.icon }}"
                                 onerror="this.src='static/images/default.jpg'"/>
                        </div>
                        <a href="{{ url_for('users.change_icon') }}">
                            <button>修改头像</button>
                        </a>
                    </div>
                    <div class="inf2">
                        <table id="infoTable">
                            <tr>
                                <td>用户名：</td>
                                <td>{{ current_user.username }}</td>
                            </tr>
                            <tr>
                                <td>邮箱:</td>
                                <td>{{ current_user.email }}</td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-md-6 column">
                <ul id="ul1">
                    <li id="li1" ><p style="font-size:14px">我的帖子</p></li>
                    <li id="li2">
                        <a href="{{ url_for('main.publish') }}"><p style="font-size:14px">我要发帖</p></a>
                    </li>
                </ul>
                <div style="width:100%;margin-top:10px;">
                    <table style="width:98%;height:260px;border: 1px solid red;margin-top:10px;">
                        <tr style="margin-left:15px">
                            <td style="width:70%;font-size:20px">内容摘要</td>
                            <td style="width:30%;font-size:20px">发表时间</td>
                        </tr>
                        {% for post in posts %}
                            <tr style="margin-left:5px">
                                <td style="width:70%"><a>{{ post.content }}</a></td>

                                <td style="width:30%">{{ moment(post.timestamp).fromNow() }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    <div style="margin-left:0px">
                        {{ pagination_show(pagination,'main.index') }}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
{#    {{ super() }}#}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/user/userspace.html
{% block title %}个人中心{% endblock %}
{% block content %}
    {% include 'common/kesheheader.html' %}
    <div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
				<li class="active">
					 <a href="#">首页</a>
				</li>
				<li class="disabled">
					 <a href="#">个人中心</a>
				</li>
				<li class="dropdown pull-right">
					 <a href="#" data-toggle="dropdown" class="dropdown-toggle">修改<strong class="caret"></strong></a>
					<ul class="dropdown-menu">
						<li>
							 <a href="{{ url_for('users.change_password') }}">修改密码</a>
						</li>
						<li>
							 <a href="#">修改邮箱</a>
						</li>
						<li>
							 <a href="#">修改头像</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	<div class="row clearfix">
		<div class="col-md-6 column">
            <ul id="ul1">个人基本资料</ul>
            <div class="div_icon">
                <img class= "Icon" src = "static/images/default.jpg" onerror="this.src='static/images/default.jpg'"/>
            </div>
            <a href="#"><button>修改头像</button></a>

{#			<form class="form-horizontal" role="form">#}
{#                <div class="div_icon">#}
{#                    <img class= "Icon" src = "static/images/default.jpg" onerror="this.src='static/images/default.jpg'"/>#}
{#                </div>#}
{#				<div class="form-group">#}
{#					 <label for="inputPassword3" class="col-sm-2 control-label">username</label>#}
{#					<div class="col-sm-10">#}
{#						<input type="text" class="form-control" id="inputPassword3" />#}
{#					</div>#}
{#				</div>#}
{#                <div class="form-group">#}
{#					 <label for="inputEmail3" class="col-sm-2 control-label">Email</label>#}
{#					<div class="col-sm-10">#}
{#						<input type="email" class="form-control" id="inputEmail3" />#}
{#					</div>#}
{#				</div>#}
{##}
{#			</form>#}

		</div>
		<div class="col-md-6 column">
			<h3>
				我的帖子
			</h3>
            <!--分页烂-->
			<ul class="pagination">
				<li>
					 <a href="#">Prev</a>
				</li>
				<li>
					 <a href="#">1</a>
				</li>
				<li>
					 <a href="#">2</a>
				</li>
				<li>
					 <a href="#">3</a>
				</li>
				<li>
					 <a href="#">4</a>
				</li>
				<li>
					 <a href="#">5</a>
				</li>
				<li>
					 <a href="#">Next</a>
				</li>
			</ul>
		</div>
	</div>
</div>

{% endblock %}